version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "MiniProject1.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*

  celery:
    build: .
    command: celery -A MiniProject1 worker --loglevel=info
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A MiniProject1 beat --loglevel=info
    depends_on:
      - redis
      - web

volumes:
  postgres_data:
