# Generated by Django 5.2 on 2025-04-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_logentry_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logentry',
            name='user',
        ),
        migrations.AddField(
            model_name='logentry',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
