# Generated by Django 5.1.6 on 2025-02-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_address_remove_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('trader', 'Trader'), ('sales_rep', 'Sales Representative'), ('customer', 'Customer')], max_length=20, null=True),
        ),
    ]
