# Generated by Django 5.1.6 on 2025-02-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsreport',
            name='report_type',
            field=models.CharField(choices=[('trading_report', 'Trading Report'), ('profit_loss', 'Profit/Loss'), ('revenue_tracking', 'Revenue Tracking')], max_length=20),
        ),
    ]
