# Generated by Django 5.1.6 on 2025-03-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsreport_report_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analyticsreport',
            old_name='generated_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='analyticsreport',
            old_name='user',
            new_name='generated_by',
        ),
        migrations.RemoveField(
            model_name='analyticsreport',
            name='data',
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='file',
            field=models.FileField(default='reports/default.pdf', upload_to='reports/'),
        ),
        migrations.AddField(
            model_name='analyticsreport',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='report_type',
            field=models.CharField(choices=[('trading', 'Trading Report'), ('sales', 'Sales Report'), ('profit_loss', 'Profit/Loss Report')], max_length=50),
        ),
    ]
